### ISSUE TITLE
Break down the Resource interface

### ISSUE THREAD

**Issue by mfcochauxlaberge** [mfcochauxlaberge/jsonapi#99]
The Resource interface currently looks like this:

```
type Resource interface {
	// Creation
	New() Resource
	Copy() Resource

	// Structure
	Attrs() map[string]Attr
	Rels() map[string]Rel
	Attr(key string) Attr
	Rel(key string) Rel

	// Read
	GetID() string
	GetType() Type
	Get(key string) interface{}
	GetToOne(key string) string
	GetToMany(key string) []string

	// Update
	SetID(id string)
	Set(key string, val interface{})
	SetToOne(key string, rel string)
	SetToMany(key string, rels []string)
}
```

This is too much.
Some ideas to break it down or remove uncessary methods:

- [x] Create a new interface named Copier with the New and Copy methods (#100)
- [x] Remove Attr and Rel (Attrs and Rels can do the job) (#101)
- [x] Remove GetID and add support for Get("id") (#105)
- [x] Remove SetID and add support for Set("id") (#104)
- [x] Remove GetToOne and GetToMany and add relationships to Get (which currently only handles attributes) (#103)
- [x] Remove SetToOne and SetToMany and add relationships to Set (which currently only handles attributes) (#103)

A simplified version could look like that:

```
type Resource interface {
	GetType() Type
	Attrs() map[string]Attr
	Rels() map[string]Rel
	Get(key string) interface{}
	Set(key string, val interface{})
}
```

**Comment by mrg0lden** [comment]
question: why are `Attrs()` and `Rels()` needed when their exact same data are available within `GetType()`?

**Comment by mfcochauxlaberge** [comment]
@mrg0lden Good question. I could simplify the `Resource` interface further by removing those two methods.

I think `GetType` arrived after `Attrs` and `Rels` and didn't think of removing those two.

**Comment by mrg0lden** [comment]
While we are at it, I think `Get()` and `Set()` need better documentation (comments above them) to clarify what's expected from them.
